IETF116: Fill in Relay Publish Interaction Sub-Section
kixelated/warp-draft pull request #127
Opened 2023-04-06 17:26 UTC by suhasHere

This PR depends on #123 and #125 

The scope of this PR is to add Relay Publish interactions. This is expected to be a starter text and we can add further clarification and details in a separate PR as we develop further.

2023-04-07 16:34 UTC, fluffy commented on draft-lcurley-warp.md
> +Relays makes use of priority order and other metadata properties from the published objects to make forward or drop decisions when reacting to congestion as indicated by the underlying QUIC stack.  T
I would say they act like clients in deciding what to send next and reference the priority section. ( which we need to add )

2023-04-07 16:34 UTC, fluffy commented on draft-lcurley-warp.md
> +
Need more detail on how they are authorized

2023-05-05 16:35 UTC, fluffy requested changes

2023-05-05 16:35 UTC, fluffy commented on draft-lcurley-warp.md
> +Relays MUST match the track id in the OBJECT message header against the active subscribers for a given track. Relays MUST NOT depend on OBJECT payload content for making forwarding decisions and MUST
I think we could get clearer text on "Relays MUST match the track id in the OBJECT message header against the active subscribers for a given track." part. Perhaps "Relays match the trackID in the object header agains the  trackID created in the Annouce transaction to know which track the object is for."

2023-05-05 16:35 UTC, fluffy commented
I think we still need to deal with the issue of who creates the TrackID but seems that can be a separate PR.

2023-05-05 21:38 UTC, kixelated requested changes

2023-05-05 21:38 UTC, kixelated commented on draft-lcurley-warp.md
> +Relays MUST match the track id in the OBJECT message header against the active subscribers for a given track. Relays MUST NOT depend on OBJECT payload content for making forwarding decisions and MUST
> Relays MUST match the track id in the OBJECT message header against the active subscribers for a given track.

`track ID` is a actually hop-by-hop property (should be renamed to `subscription ID`). Each downstream subscription may use different subscription IDs, which may not match the upstream subscription ID either, so it's not quite as simple as matching them. 

And again these are weird MUSTs. What happens if a relay... doesn't do this? In fact I would want relays to be able to rewrite track names, so it's not clear how that would even work with this assertive yet unenforceable statement.

2023-05-05 21:38 UTC, kixelated commented on draft-lcurley-warp.md
> +The "ANNOUNCE" message advertises set of tracks, identified via their Full Track Names ({{model-track}}) and carry necessary authorization information. Relays MUST
Are multiple ANNOUNCE messages allowed? What happens when authentication needs to be renewed? Can an endpoint UNANNOUNCE tracks...? What happens if another endpoint ANNOUNCEs the same track (ex. reconnection)?

2023-05-05 21:38 UTC, kixelated commented on draft-lcurley-warp.md
> +The "ANNOUNCE" message advertises set of tracks, identified via their Full Track Names ({{model-track}}) and carry necessary authorization information. Relays MUST
How does the receiver identify tracks? 

In order to support ingestion from generic clients (like OBS), we need some way of identifying the catalog; it can't be negotiated out-of-band. I included the track format in my proposal to this end. 

@vasilvv suggested ending the track name with a `/` if it's a catalog, which is kind of neat since a catalog is like a directory listing. I think ending with `/catalog_v0` is more future proof, although I would like to see a registry rather than encoding behavior into the track name,.

2023-05-05 22:33 UTC, kixelated commented on draft-lcurley-warp.md
> +Relays respond with "ANNOUNCE OK" and/or "ANNONCE ERROR" control messages reflecting the authorization status.
edit: I do think we need these messages primarily to add an `expires` field in ANNOUNCE OK similar to SUBSCRIBE OK. I would really like to combine authentication in both though.

2023-05-12 16:09 UTC, afrind commented on draft-lcurley-warp.md
> +OBJECT message header carry short hop-by-hop `Track Id` that maps to the "Full Track Name". Relays MUST use the `Track Id` in the incoming OBJECT messages to find active subscribers with track inform
Individual/Editorial comment

> Relays MUST use the `Track Id` in the incoming OBJECT messages to find active subscribers with track information matching the `Track Id`.

This MUST reads a little prescriptive to me.  Maybe rewrite the sentence without the MUST and make it informative rather than normative, like:

`Relays use the `Track ID` of an incoming OBJECT message to identify its track and find the active subscribers for that track`

2023-05-12 16:24 UTC, suhasHere commented on draft-lcurley-warp.md
> +OBJECT message header carry short hop-by-hop `Track Id` that maps to the "Full Track Name". Relays MUST use the `Track Id` in the incoming OBJECT messages to find active subscribers with track inform
Without that MUST, I am not sure what's the source of truth in object message to find the track information

2023-05-14 23:11 UTC, suhasHere commented on draft-lcurley-warp.md
> +The "ANNOUNCE" message advertises set of tracks, identified via their Full Track Names ({{model-track}}) and carry necessary authorization information. Relays MUST
i do think we need to answer/clarify on some of these , but it's not in the scope of this PR.

2023-05-15 21:14 UTC, afrind reviewed
Individual review

2023-05-15 21:14 UTC, afrind commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
Same concern about common prefix -- can we say "Full Track Name matches the announced namespace"?

2023-05-15 22:40 UTC, suhasHere commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
Full Track Name includes both Track Namespace and Track Name, so here the match should happen only on the namespace part. I wonder if the suggestion is saying namespace is the full track name

2023-05-15 22:44 UTC, afrind commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
Hmm, yeah I agree that could be a reading of it which I didn't intend. Maybe:

> set of tracks whose Track Namespace matches the announced namespace

2023-05-16 18:09 UTC, kixelated commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
This text is duplicated in both the ANNOUNCE and SUBSCRIBE section... but is slightly different. Can you move it to it's own "authorization" sub-second?

2023-05-16 18:21 UTC, kixelated commented on draft-lcurley-warp.md
> +OBJECT message header carry short hop-by-hop Track Id that maps to the Full Track Name (see {{message-subscribe-ok}}). Relays use the Track ID of an incoming OBJECT message to identify its track and
> OBJECT message header carry short hop-by-hop Track Id that maps to the Full Track Name (see {{message-subscribe-ok}}). Relays use the Track ID of an incoming OBJECT message to identify its track and find the active subscribers for that track.

What does this have to do with publishing? This whole paragraph should be in the subscription section... it even mentions subscribers.

> Unless determined by congestion response, Relays MUST forward the OBJECT message to the matching subscribers.

If it's not enforceable, then it's a SHOULD and not a MUST. We should also have a discussion about if a transmuxer / transcoder is a "relay".

2023-05-16 20:13 UTC, afrind commented on draft-lcurley-warp.md
> +OBJECT message header carry short hop-by-hop Track Id that maps to the Full Track Name (see {{message-subscribe-ok}}). Relays use the Track ID of an incoming OBJECT message to identify its track and
> We should also have a discussion about if a transmuxer / transcoder is a "relay".

I think we have had this discussion, right?  A relay doesn't have access to the raw media / e2e encryption keys so a transmuxer / transcoder is not a relay, it's a subscriber and publisher glued together.

2023-05-16 20:33 UTC, suhasHere commented on draft-lcurley-warp.md
> +OBJECT message header carry short hop-by-hop Track Id that maps to the Full Track Name (see {{message-subscribe-ok}}). Relays use the Track ID of an incoming OBJECT message to identify its track and
i was defining transcoder as https://datatracker.ietf.org/doc/html/draft-nandakumar-moq-arch-00#section-2.2

it has following security roles publisher, subscriber, emitter and receiver

2023-05-16 20:34 UTC, suhasHere commented on draft-lcurley-warp.md
> +OBJECT message header carry short hop-by-hop Track Id that maps to the Full Track Name (see {{message-subscribe-ok}}). Relays use the Track ID of an incoming OBJECT message to identify its track and
> What does this have to do with publishing? This whole paragraph should be in the subscription section... it even mentions subscribers.

this is needed to tell what is relay doing when a publish happens

2023-05-16 20:35 UTC, suhasHere commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
once we refactor to have common sender/receiver section , it would be more clearer to move things around inside the relay section. I know its duplicate, but would prefer to fix in a separate PR though

2023-05-16 20:43 UTC, afrind commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
@suhasHere : do you agree with matching namespaces rather than matching prefixes?

2023-05-16 20:45 UTC, suhasHere commented on draft-lcurley-warp.md
> +Relays respond with "ANNOUNCE OK" and/or "ANNONCE ERROR" control messages providing the results of announcement.
This section is about Relays and using relays goes along with previous page. I think the above change can be part of #153

2023-05-16 20:53 UTC, suhasHere commented
@kixelated  I did try to respond to your comments. I do agree in general with refactoring suggestions, however, I feel it can done as part of #153

2023-05-16 21:26 UTC, suhasHere commented on draft-lcurley-warp.md
> +- Verifying that the publisher is authorized to publish the content associated with the set of tracks whose Full Track Name share a common prefix with the announced namespace. Specifics of where the
yes @afrind

2023-05-16 22:22 UTC, kixelated approved these changes
it's fine, we can do an editorial pass later to consolidate the publisher/subscriber/authentication/relay text

2023-05-16 22:27 UTC, merged