IETF116: Fill in Relay sub-sections on discovery and connection restoration
kixelated/warp-draft pull request #128
Opened 2023-04-06 17:34 UTC by suhasHere

This PR depends on #125

2023-04-07 16:37 UTC, fluffy approved these changes

2023-04-07 16:37 UTC, fluffy commented on draft-lcurley-warp.md
My preference would be to add a TBD here of open issue on relay discovery.

2023-04-07 16:37 UTC, fluffy commented on draft-lcurley-warp.md
> +DISCUSS: do we need to describe here the "subscribe intent"? Do we want to reuse the concept of "groups" or are these specific to tracks? Timestamps may be very useful, but do we need to attach times
Rephrase in terms of requirements and possible behavior we could want.

2023-05-05 16:25 UTC, afrind reviewed
Individual review.

Rebase for readability.

I'm not sure what's different about restoring a connection through a relay vs direct-to-publisher - most of the text here doesn't seem relay specific.

2023-05-05 16:25 UTC, afrind commented on draft-lcurley-warp.md
> +Relays are discovered via application defined ways that are out of scope of this document. A Relay that wants to shutdown can send a message to the client with the address of new relay. Client moves
Do we need to define the message for accomplishing this?

2023-05-05 16:25 UTC, afrind commented on draft-lcurley-warp.md
> +Relays are discovered via application defined ways that are out of scope of this document. A Relay that wants to shutdown can send a message to the client with the address of new relay. Client moves
I assume that closing the connection will implicitly unsubscribe, so explicitly unsubscribing seems redundant.

2023-05-05 16:25 UTC, afrind commented on draft-lcurley-warp.md
> +There is no guarantee that the restored connectivity will have the same characteristics as the previous instance. The throughput might be lower, forcing the subscriber to select a media track with lo
This bit seems opposed to the above text "Client moves to the new relay with all of its Subscriptions" - maybe needs to be reworded into a single section that explains the nuance of migration?

2023-05-05 16:25 UTC, afrind commented on draft-lcurley-warp.md
> +DISCUSS: do we need to describe here the "subscribe intent"? Do we want to reuse the concept of "groups" or are these specific to tracks? Timestamps may be very useful, but do we need to attach times
I think it would be useful to how how groups can be used during migration.  Since the transport protocol is not currently aware of timestamps, I have a preference to rely on groups, at least for now, and let applications or streaming formats handle the group/timestamp mappings?

2023-05-05 22:03 UTC, kixelated requested changes
The reconnect stuff is biting off a MUCH bigger issue that needs very careful consideration.

2023-05-12 15:46 UTC, afrind commented
Since we agreed to table connection restoration until after adoption, should we close this PR for now?

2023-05-14 23:07 UTC, suhasHere commented
closing and will reopen once draft is adopted

2023-05-14 23:07 UTC, closed without merging