Define the protocol over raw QUIC
kixelated/warp-draft pull request #135
Opened 2023-04-12 21:13 UTC by vasilvv

2023-04-13 15:18 UTC, suhasHere commented on draft-lcurley-warp.md
> +~~~~~~~~~~~~~~~
for my better understanding on why we need a elaborate URI scheme
- why do we need path ? and how is it set ?
- what is the usecase for query ?

2023-04-13 15:23 UTC, suhasHere commented on draft-lcurley-warp.md
Native QUIC would be my inclination to call it out though :-)

2023-04-13 18:00 UTC, huitema requested changes
The definition of raw QUIC suggests using a "path" parameter, but there is no such thing in QUIC itself. The use of the path parameter is largely linked to the discussion of bundling, and that discussion has not yet concluded. Waiting for that, I believed we have agreed to not consider bundling in the version-00 of the transport draft, and to simply let the client subscribe to a bunch of tracks, each with their own URI. Maybe mark the whole "path" discussion as "for further study"?

2023-04-13 18:00 UTC, huitema commented on draft-lcurley-warp.md
There is no "path" parameter in raw QUIC. If we do want one, we will have to define some kind of "SETTINGS" transaction to specialize the QUIC/MoQ connection, but it may be a bit early to define that. I would replace this paragraph by a place-holder for now, something like: "TODO: define whether the `path` parameter is actually needed for raw QUIC connections, and if it is define how to carry it. Waiting for that, assume that the `path` parameter is empty when using raw QUIC."

2023-04-14 14:58 UTC, vasilvv commented on draft-lcurley-warp.md
Renamed.

2023-04-14 14:58 UTC, vasilvv commented on draft-lcurley-warp.md
> +~~~~~~~~~~~~~~~
It isn't really elaborate -- I just made it equivalent to what HTTP supports.  We could potentially drop path/query, though that can be a useful routing lever.

2023-04-14 14:58 UTC, vasilvv commented on draft-lcurley-warp.md
> If we do want one, we will have to define some kind of "SETTINGS" transaction to specialize the QUIC/MoQ connection, but it may be a bit early to define that.

This document already defines one (and we in fact discussed in #107).

2023-04-19 18:27 UTC, kixelated approved these changes
LGTM

2023-04-19 18:27 UTC, kixelated commented on draft-lcurley-warp.md
> +the PATH parameter ({{path}}).
Needs some further explanation.

> ...in the SETUP message after establishing the QUIC connection.

2023-04-19 18:27 UTC, kixelated commented on draft-lcurley-warp.md
Yeah, this `SETUP` message is that `SETTINGS` transaction you're talking about @huitema .

2023-04-19 21:13 UTC, huitema commented on draft-lcurley-warp.md
Yes, that would work. I am a bit worried about the setting mechanism itself -- "the first bidir stream from the client" seems like a bit underspecified, given that the order in which the stream opening order is not guaranteed the same as client and server. But assuming we fix that, yes, sending "role", "path", and probably "version" on a setup stream makes sense. In raw QUIC, I would assume that the setup could be sent in 0-RTT.

2023-04-20 00:50 UTC, suhasHere commented on draft-lcurley-warp.md
just want to make sure that we are moving the path and query parameter to SETTINGS ? since atleast for now, I am not sure how it applies to native QUIC ..

2023-04-20 00:51 UTC, suhasHere requested changes
just want to make sure that we are moving the path and query parameter to SETTINGS ? since atleast for now, I am not sure how it applies to native QUIC ..

2023-04-20 01:15 UTC, kixelated commented
> just want to make sure that we are moving the path and query parameter to SETTINGS ? since atleast for now, I am not sure how it applies to native QUIC ..

No Suhas, the path is in the SETUP message. There's no SETTINGS message for native QUIC. 

I was alluding to how the SETUP message performs a similar role to the HTTP/3 SETTINGS message. Both endpoints negotiate functionality, but in the case of native QUIC, also exchange a connection URL.

2023-04-20 05:42 UTC, huitema commented on draft-lcurley-warp.md
> +~~~~~~~~~~~~~~~
I really wonder what the point of QUERY parameters would be, if we have an explicit SETUP process. That would mean two option for specifying parameters: as SETUP type/value, or as query items. Leading to potential conflicts, etc.

We had discussions in previous meetings of using the Path parameter to specify some kind of "bundle", maybe a common origin for the tracks. But that too would be better handled by a specific SETUP type/value.

That means we could also simplify the HTTP specification, and explain that the only purpose of the path-abempty would be to distinguish MoQ from other webtransport services implemented on the server -- pretty much the equivalent of the ALPN.

2023-04-21 14:13 UTC, suhasHere commented
> > just want to make sure that we are moving the path and query parameter to SETTINGS ? since atleast for now, I am not sure how it applies to native QUIC ..
> 
> The path is in the SETUP message. There's no SETTINGS message for native QUIC and it's transparent anyway to MoQ over WebTransport.
> 
> I was alluding to how the SETUP message performs a similar role to the HTTP/3 SETTINGS message. Both endpoints negotiate functionality, but in the case of native QUIC, also exchange a connection URL.


Sorry for the confusion , yes I meant SETUP message. The PR currently specifies PATH and query in the connection URL for native QUIC, which may be reworded under a TODO for now. Other than that, we should be fine ?

2023-04-21 19:04 UTC, suhasHere approved these changes

2023-04-21 19:22 UTC, merged