Flesh out group properties.
kixelated/warp-draft pull request #147
Opened 2023-04-26 18:53 UTC by kixelated

It was quite difficult to get the wording correct and I'm open to suggestions.

The main difficult is that groups are not truly independent, particularly for audio decoding. In Yokohama I learned I was mistaken in the assumption that audio consists of independent "frames"; technically it self-corrects any errors. This was extra apparent in my sample code as reseting the decoder at each group caused noticeable blips (we can remove this anecdote from the text if it's not useful). Video works the same way when using intra-refresh so we need to clearly spell it out.

2023-04-26 18:54 UTC, kixelated commented
Replaces #90.

2023-04-26 20:20 UTC, afrind reviewed
Individual review, mostly editorial comments.

2023-04-26 20:20 UTC, afrind commented on draft-lcurley-warp.md
> +Each group is a join point, such that a new subscriber can begin receiving a track without prior progress.
'receiving' doesn't strike me as the right verb.  'consuming' as in the previous text was probably ok, or using/decoding/processing?

2023-04-26 20:20 UTC, afrind commented on draft-lcurley-warp.md
> +Each group is a join point, such that a new subscriber can begin receiving a track without prior progress.
'prior progress' reads awkwardly to me.  Something similar to the previous text might work "without access to any other groups"

2023-04-26 20:20 UTC, afrind commented on draft-lcurley-warp.md
> +This implies that the first object within a group MUST NOT depend on other objects.
I don't think you need "This implies that".

2023-04-26 20:20 UTC, afrind commented on draft-lcurley-warp.md
> +However, the sender MUST still transmit objects based on the priority {{send-order}}, not based on the group sequence number.
I'm a bit confused by this part.  Maybe leave it out for now since it doesn't seem purely object model related - the priority stuff can go in the priority section?

2023-04-26 20:20 UTC, afrind commented on draft-lcurley-warp.md
> +A decoder MAY use objects from prior groups when using a self-correcting encoding scheme.
I'm trying to reconcile "MUST NOT depend" with "MAY use".  It sounds like there's some encoding schemes that have "weak" rather than strict dependencies.  I would maybe put this MAY up near line 220/221 at least.

2023-04-27 04:41 UTC, suhasHere requested changes
Thanks for the PR and few high level comments

At a higher level, it might be useful to capture group properties as
- Groups are consumption points for enabling functions like joins, rewinds and replays
- Groups are checkpoints for nodes implementing relay functionality to implement appropriate congestion responses
- Some text about object dependencies within a group

2023-04-27 04:41 UTC, suhasHere commented on draft-lcurley-warp.md
> +However, the sender MUST still transmit objects based on the priority {{send-order}}, not based on the group sequence number.
+1 to @afrind  suggestion. This doesn't seem to fit in the data model section and the SHOULD here is probably  making it a suggestion.

2023-04-27 04:41 UTC, suhasHere commented on draft-lcurley-warp.md
> +A decoder MAY use objects from prior groups when using a self-correcting encoding scheme.
I don't see how this helps with the data model and also may be we should replace the decoder here with "application" to be generic

2023-04-27 04:41 UTC, suhasHere commented on draft-lcurley-warp.md
I think we still need " is starts at 0 at the original media publisher".  A subscriber joining mid-way through a call will be delivered object message with group_sequence > 0.

2023-04-27 04:41 UTC, suhasHere commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
I don't think "MUST be decodable after the delivery of all prior objects" is true. Decoders can decode a p-frame even if its proir p-frame is missing, but the experience for the user will not be great. 

May be somethign on these lines ?

1) Objects within a group express dependency relationship and in certain application settings an object MAY NOT be decodable until all the prior objects are delivered.

2) "Also, the first object within a group MUST NOT depend on other objects within a group"

2023-04-27 15:12 UTC, afrind reviewed
Individual/Editorial comments

2023-04-27 16:13 UTC, suhasHere commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
my concern is the requirement of delivery .. MAY NOT was suggested to say that it is true in some cases not all the cases.

2023-04-27 16:25 UTC, afrind commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
I think we're all saying the same thing.  Maybe it's easier to read this normative requirement if it were in the active rather than passive voice:

An endpoint MUST NOT add an object to a group if that object strictly depends on an object in another group, or another object in the same group with a higher sequence number.

?

2023-04-27 21:54 UTC, suhasHere commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
that is not true entirely .. when there are B frames, there will be dependency in both directions .. 

These details are very specific to media encoding and these might totally change when a new codec come.

I would rather keep it at an higher level and suggest something on the lines of " objects within a group express dependency relationship and the first object must be the independent object."

We can then add few example for video coding , but those are just examples and not normative requirements.

2023-04-27 22:17 UTC, afrind commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
Good point about B frames - let me make sure I understand:

The dependency graph is like this:  P1 <- B -> P2 (and also maybe P1 <- P2?)

And an app might want to put B and P2 in the same group, but transmit B first because it's available first, right?

I was thinking that making stricter normative guarantees about group properties would make publisher, relay and receiver operation easier, but with graphs like these maybe there isn't anything we can definitively say.

When an encoder spits out a B frame, does it know how many subsequent frames it's going to depend on?  If so, the publisher could send P1(seq=0), B(seq=2), P2(seq=1), but maybe that opens up another can of worms.

2023-04-28 02:18 UTC, suhasHere commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
An application knows exactly based on the encoding scheme its dependency structure and it can use techniques to order the objects that satisfy the relationship. I feel we should probably not define more about these specifics in this spec

2023-04-28 02:45 UTC, kixelated commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
@suhasHere media should always* be transmitted in decode order (DTS), not presentation order (PTS).

The object sequence is basically the same thing as DTS but sequential. A B-frame would have a higher object sequence than any frames it references.

I think the sequential nature is useful because a relay can detect gaps. A relay can guarantee that an object is decodable if all prior sequences have been delivered, without access to the underlying frame references.

2023-04-28 02:56 UTC, kixelated commented on draft-lcurley-warp.md
> +A decoder MAY use objects from prior groups when using a self-correcting encoding scheme.
I think this mostly points out a flaw with the concept of groups. They can't actually provide hard dependency guarantees.

Personally, I think we should position groups as the addressable units, while objects are merely chunks within a group.

2023-04-28 03:02 UTC, kixelated commented on draft-lcurley-warp.md
I see what you mean. Is there a better way to phrase "at the original media publisher"? Could we just remove this "starts at zero" altogether?

2023-04-28 03:09 UTC, kixelated commented
> * Groups are consumption points for enabling functions like joins, rewinds and replays
> * Groups are checkpoints for nodes implementing relay functionality to implement appropriate congestion responses

I'm having trouble explaining WHY groups can be used as sync points or checkpoints. What are the concrete properties of groups that enable these use-cases?

2023-04-28 03:54 UTC, suhasHere commented on draft-lcurley-warp.md
> +A decoder MAY use objects from prior groups when using a self-correcting encoding scheme.
Objects are sequenced when inserted into the group, the delivery can have gaps (due to drops) or out of sequence .. But the application knows to put them in order. 

May be we need to say "Nodes SHOULD always attempt to deliver objects within the group as defined by its object sequence, wherever possible"

2023-04-28 04:03 UTC, suhasHere commented
> > * Groups are consumption points for enabling functions like joins, rewinds and replays
> > * Groups are checkpoints for nodes implementing relay functionality to implement appropriate congestion responses
> 
> I'm having trouble explaining WHY groups can be used as sync points or checkpoints. What are the concrete properties of groups that enable these use-cases?

Consumption points - subscriber joins, rewind and replays
Checkpoints - For relays to apply congestion response at group boundaries

2023-04-28 05:44 UTC, suhasHere commented on draft-lcurley-warp.md
may be say it as "group sequence start at 0 however subscribers should be able to consume objects starting at any group sequence" ??

2023-04-28 17:02 UTC, kixelated commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
> I don't think "MUST be decodable after the delivery of all prior objects" is true. Decoders can decode a p-frame even if its proir p-frame is missing, but the experience for the user will not be great.

If all prior frames have been delivered, then yeah, the P-frame MUST be decodable. But like Alan said, I was careful to not say anything about the opposite case. I agree that we can't say that "an object MUST NOT be decodable without all prior frames".

2023-04-28 17:36 UTC, kpugin commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
> The object sequence is basically the same thing as DTS but sequential. A B-frame would have a higher object sequence than any frames it references.

hm... DTS of B-frame would be lower than DTS of P-frame it depends on - am I messing up something? In that case how does sequence number of B frame can be higher than all frames it depends on?

2023-04-28 17:46 UTC, fluffy commented on draft-lcurley-warp.md
> +However, the sender MUST still transmit objects based on the priority {{send-order}}, not based on the group sequence number.
I think we should just remove lines 225 to 226 and move to the section on how senders decide what to send next.

2023-04-28 17:49 UTC, fluffy commented on draft-lcurley-warp.md
> +An object MUST be decodable after the delivery of all prior objects within the same group.
I propose we resolve this by removing the word "prior"

2023-05-05 16:32 UTC, suhasHere commented on draft-lcurley-warp.md
i think the latest commit didn't fix this yet ?

2023-05-05 16:32 UTC, suhasHere commented on draft-lcurley-warp.md
> +In general, objects within a group SHOULD NOT depend on objects in other groups.
I am inclining that we just skip this sentence altogether ?

2023-05-05 16:33 UTC, suhasHere commented on draft-lcurley-warp.md
> +A group behaves as a join point for subscriptions.
May be also add a point for relays to make congestion response decisions.

2023-05-05 16:44 UTC, fluffy approved these changes

2023-05-05 16:44 UTC, fluffy commented on draft-lcurley-warp.md
I would be happy to see this merged either way.

2023-05-05 17:05 UTC, kixelated commented on draft-lcurley-warp.md
Oh yeah I forgot about this section.

2023-05-05 17:15 UTC, vasilvv approved these changes

2023-05-05 17:15 UTC, suhasHere approved these changes

2023-05-05 17:22 UTC, merged