Clarify that objects may be partially decodable.
kixelated/warp-draft pull request #148
Opened 2023-04-26 18:58 UTC by kixelated

Removes a discuss in the object model, going with option 1.

I do think we should add an atomic/incremental flag to OBJECT, so the relay can know when dropping an object early will cause an object to be full undecodable.

2023-04-26 20:07 UTC, afrind reviewed
Editorial suggestions

2023-04-26 20:07 UTC, afrind commented on draft-lcurley-warp.md
> +The application MAY be able to partially decode an object.
Maybe 'decode a partially received object' ?

2023-04-26 20:07 UTC, afrind commented on draft-lcurley-warp.md
> +A sender SHOULD transmit incomplete objects to avoid incurring additional latency.
A sender SHOULD transmit partial object data as soon as possible to avoid incurring additional latency.

2023-04-26 20:07 UTC, afrind commented on draft-lcurley-warp.md
> +A sender MAY drop or deprioritize the remainder of an object during congestion,
The meaning of 'remainder' is unclear - remainder after what?  Maybe:

A sender MAY drop or deprioritize object data during congestion, potentially rendering an object undecodable in favor of a higher priority object.

2023-04-26 20:08 UTC, afrind commented on draft-lcurley-warp.md
> +objects: such objects are members of the same group {{model-group}}. Objects carry
We lost the statement 'All objects belong to a group' - which I think was providing some value.  Maybe put it first like:

All objects belong to a group.  An object MAY depend on other objects in the same group.

2023-04-27 04:13 UTC, suhasHere requested changes

2023-04-27 04:13 UTC, suhasHere commented on draft-lcurley-warp.md
> +objects: such objects are members of the same group {{model-group}}. Objects carry
+1 to @afrind  suggestion on ``` All objects belong to a group. An object MAY depend on other objects in the same group.```

Also , I think we still need it to be cacheable unit too,  since it will give Relays unit of caching as objects and can support object queries to be served from cache

2023-04-27 04:13 UTC, suhasHere commented on draft-lcurley-warp.md
> +A relay MUST NOT combine, split, or otherwise modify object payloads.
+1 on "MUST NOT combine, split, or otherwise modify object payloads"

2023-04-27 04:13 UTC, suhasHere commented on draft-lcurley-warp.md
> +The application MAY be able to partially decode an object.
per our 1:1 chat at IETF116, we agreed to not mention anything about partially decodable property. I would prefer removing this line altogether. I think it is application way to define object granularity ( GOP vs single frame, for example) and they know if they are partially decodable or not.

2023-04-27 04:13 UTC, suhasHere commented on draft-lcurley-warp.md
> +A sender SHOULD transmit incomplete objects to avoid incurring additional latency.
Again, I will remove this sentence and not useful for the data model section and also "partial" is not well defined.  

How about we have something on these lines 
"Latency sensitive applications using moq-transport MAY choose not to wait for the object to be fully constructed before transmitting. The mechanisms of how the parts of the objects are identified at the receiver is defined by the application"

2023-04-27 04:13 UTC, suhasHere commented on draft-lcurley-warp.md
> +A sender MAY drop or deprioritize the remainder of an object during congestion,
I am not sure this level of detail is needed in data model section

2023-04-27 15:00 UTC, afrind reviewed
Individual review/editorial

2023-04-27 16:00 UTC, suhasHere commented on draft-lcurley-warp.md
> +A sender SHOULD transmit incomplete objects to avoid incurring additional latency.
in my intent above, i was thinking of just the end-points and hence used the word Applications.  I agree we can add a section on relays above too.

2023-04-27 22:55 UTC, kixelated commented on draft-lcurley-warp.md
> +A sender SHOULD transmit incomplete objects to avoid incurring additional latency.
> This would work for me too, although the statement is largely aimed at relays, rather than endpoints. I'm guessing Luke was trying to be generic with "sender" but maybe spelling out the relay bit is also useful, like

I want to make sure that MoQ libraries support streaming objects too. The intention is to signal that generic libraries and endpoints should not buffer objects.

bad: `send_object(id: int, payload: bytes)`
good: `start_object(id: int); write(chunk: bytes); write(chunk: bytes)`

> in my intent above, i was thinking of just the end-points and hence used the word Applications.

I only think of the "application" as the first and last hop. A generic relay has no idea that an application is "latency sensitive", and can't change its behavior in response.


> I will remove this sentence and not useful for the data model section and also "partial" is not well defined.

I want OBJECTs to behave like QUIC streams, where they could be used for both incremental (partially buffered) and atomic (fully buffered) purposes. I think it's important to clarify that somehow.

2023-04-27 22:55 UTC, kixelated commented on draft-lcurley-warp.md
> +A sender MAY drop or deprioritize the remainder of an object during congestion,
I think it's important to mention that an object might not be delivered, without going into detail. Although we can remove stuff about partial objects because those fall into the same "might not be (fully) delivered" bucket.

2023-04-27 22:55 UTC, kixelated commented on draft-lcurley-warp.md
> +objects: such objects are members of the same group {{model-group}}. Objects carry
> Also , I think we still need it to be cacheable unit too, since it will give Relays unit of caching as objects and can support object queries to be served from cache

I just don't know what "cacheable" means. I think it's fair to say that an object is addressable and that TTL is an example property. But otherwise, I don't think anything is being added by including that word.

2023-04-28 17:10 UTC, afrind commented on draft-lcurley-warp.md
> +An object MAY arrive out of order or dropped altogether.
or *be* dropped

2023-05-04 21:43 UTC, suhasHere approved these changes

2023-05-05 16:41 UTC, fluffy approved these changes

2023-05-05 17:06 UTC, merged