Remove any references to media.
kixelated/warp-draft pull request #156
Opened 2023-05-17 23:10 UTC by kixelated

Going to be moved to another draft that uses tracks.
Will rename the file to `draft-moq-transport` after this gets merged.

2023-05-17 23:27 UTC, vasilvv commented on draft-lcurley-warp.md
> +: An QUIC connection identified via a URL after a handshake.
I'm not sure this is necessarily true -- you can have multiple WT sessions on a QUIC connection, for instance.  Was there anything wrong specifically with the old transport session definition?

2023-05-17 23:27 UTC, vasilvv commented on draft-lcurley-warp.md
> +: An endpoint that publishes tracks and transmits objects over the network.
"Publisher is an endpoint that publishes" -- that is a bit of a circular definition.  Maybe, since we always require subscribing, we could use something along the lines of "publisher is an endpoint that fulfills the subscription requests and sends objects?"

2023-05-17 23:27 UTC, vasilvv commented on draft-lcurley-warp.md
> +: A live stream, fragmented into objects that are generated over time.
I feel like "a live stream" is ambiguous.  A sequence of objects?  A stream of objects?  A feed of objects?

2023-05-17 23:44 UTC, suhasHere requested changes
Thanks for the PR .. Few nits on terminology and suggestions on some.

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> +: The initial publisher that encodes tracks and objects.
I would either refer to the terminology defined in https://datatracker.ietf.org/doc/html/draft-nandakumar-moq-arch-00#section-2 or copy some sort of these.

Since there is security role played by each entity and it will be good to define along those lines.

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
group/object -> prefer add a reference to the model section

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> +The application is responsible for determining how tracks are named, encoded, or otherwise used.
i don't think the last statement is needed.

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> -~~~
Let's please add the examples back.

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> +The speed at which a live protocol can detect and respond to queuing determines the latency.
s/live protocol/moq-transport protocol

Live protocol seems bit ambigouos or partly defined.

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> +The live media protocol ecosystem is fragmented; each protocol has it's own niche.
s/live media protocol/moq-transport protocol

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> +The ability to scale a protocol actually depends on relay support: proxies, caches, CDNs, SFUs, etc.
I feel by remove the term media, we are loosing clarity here.
to scale a "to scale a live media protocol " is still fine. Media doesn't have to me audio or video. Or may be reword it as "to scale a live content delivery transport"

2023-05-17 23:44 UTC, suhasHere commented on draft-lcurley-warp.md
> +A OBJECT message contains a byte slice associated with a specified track, as well as associated metadata required to deliver, cache, and forward it.
A OBJECT message contains a byte slice or A OBJECT message contains chunk of data ?

2023-05-17 23:46 UTC, suhasHere commented on draft-lcurley-warp.md
>  abbrev: WARP
Pleas rename WARP to MoQTransport .

s/Warp - Live Transport over QUIC/MoQTransport - Live  Content Transport Protocol over QUIC

2023-05-17 23:47 UTC, suhasHere requested changes

2023-05-18 01:23 UTC, afrind reviewed
Individual/editorial review

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +The speed at which a live protocol can detect and respond to queuing determines the latency.
Since this is about motivation, I don't think using moq-transport-protocol here is necessary.  Maybe just

`The speed at which the system can detect and respond...?`

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +The live media protocol ecosystem is fragmented; each protocol has it's own niche.
I think `live media protocol ecosystem` is correct here, or maybe just `media protocol ecosystem`

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +And then distribute other live content over other protocols: for example updates, chat, metadata, etc.
This is not a sentence.

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +This draft attempts to build a unified base live transport for media and similar use-cases.
s/base live transport/base transport protocol/ ?

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +No error occurred, however the endpoint wishes to terminate.
terminate the session.

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +A OBJECT message contains a byte slice associated with a specified track, as well as associated metadata required to deliver, cache, and forward it.
Byte slice came out of nowhere.  Maybe 

`An OBJECT message contains a range of contiguous bytes from a track, ...`

Though this now begs the questions about whether Object metadata should also carry the offset into the track (maybe?, optionally?), and whether data from multiple OBJECTs can overlap (hopefully not).

2023-05-18 01:23 UTC, afrind commented on draft-lcurley-warp.md
> +: Only the client is expected to send object on the connection. This is commonly referred to as *the ingestion case*.
objects

2023-05-18 02:22 UTC, suhasHere commented on draft-lcurley-warp.md
>  abbrev: WARP
The comment indicates file name rename .. May be my confusion?

2023-05-18 17:16 UTC, suhasHere commented on draft-lcurley-warp.md
> +: The initial publisher that encodes tracks and objects.
that would be fine too and also bringing something as informational reference shouldn't be bad either

2023-05-18 17:17 UTC, suhasHere commented on draft-lcurley-warp.md
> +: An endpoint that publishes tracks and transmits objects over the network.
This is what is currently defined in the arch spec
"Entities with Publisher role publish MoQ Objects belonging to a given track using the MoQ Transport Protocol."

2023-05-18 17:22 UTC, suhasHere commented on draft-lcurley-warp.md
> +: An endpoint that publishes tracks and transmits objects over the network.
May be we can do it in its own PR. Created an issue to discuss the same here: https://github.com/kixelated/warp-draft/issues/157

2023-05-20 20:29 UTC, fluffy commented on draft-lcurley-warp.md
> +: The initial publisher that encodes tracks and objects.
+1 one on getting all the definitions this draft needs into this draft.

2023-05-20 20:32 UTC, fluffy commented on draft-lcurley-warp.md
> +: A live stream, fragmented into objects that are generated over time.
To help the reader understand, I think it would be useful to give and an example along lines of "a track would often be used to represent a single stream of video, or audio". Something that ties it back to media and helps the reader understand what this might be.

2023-05-20 20:33 UTC, fluffy commented on draft-lcurley-warp.md
> +: A collection of objects, used to denote join points for new subscribers.
Might be good to add in that a group is part of a single track.

2023-05-20 20:38 UTC, fluffy commented on draft-lcurley-warp.md
>  ## Latency
FWIW ... in this section, I think it would be fine to talk about media instead of content but I am fine with it either way

2023-05-20 21:52 UTC, fluffy commented on draft-lcurley-warp.md
>  Bufferbloat is caused by routers queueing packets for an indefinite amount of time rather than drop them.
I might rephrase this as something like .... "Bufferbloat occurs when routers queue packets for too long instead of dropping the packet which can add significant latency."

2023-05-20 21:57 UTC, fluffy approved these changes
I added some small comments which can be incorporated or ignored as you see fit. I think this does a good job of the the main goal of moving th media part to  the other draft.

2023-05-20 22:30 UTC, kixelated commented on draft-lcurley-warp.md
>  ## Latency
I'd like to move this motivation section to an overview or requirements document, and yeah make it media-specific.

2023-05-20 22:30 UTC, kixelated commented on draft-lcurley-warp.md
> -~~~
Sorry, I got carried away.

2023-05-20 22:30 UTC, kixelated commented on draft-lcurley-warp.md
> -~~~
FYI the examples could be shorter.

```
/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(182): Warning: Artwork too wide, reducing indentation from 3 to 0
/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(170): Warning: Section too wide, reducing indentation from 0 to 0
/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(165): Warning: Section too wide, reducing indentation from 0 to 0
/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(140): Warning: Section too wide, reducing indentation from 0 to 0
/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(66): Warning: Middle too wide, reducing indentation from 0 to 0
s/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(182): Warning: Too long line found (L286), 8 characters longer than 72 characters:
Track Namespace = videoconferencing.example.com/meetings/m123/participants/alice
/Users/kixelated/work/warp-draft/draft-lcurley-warp.xml(182): Warning: Too long line found (L288), 14 characters longer than 72 characters:
Full Track Name = videoconferencing.example.com/meetings/m123/participants/alice/audio
```

2023-05-21 09:32 UTC, kixelated commented on draft-lcurley-warp.md
> +: An endpoint that publishes tracks and transmits objects over the network.
I agree, but I removed the changes to the definitions anyway.

2023-05-21 09:43 UTC, kixelated commented on draft-lcurley-warp.md
> +: The initial publisher that encodes tracks and objects.
I removed any changes to the definitions because it was out of place.

off-topic: I wouldn't define the producer as the entity with encryption keys, especially because that's optional. The producer's main role is to package live content into tracks/groups/objects. There should definitely be a note saying the producer SHOULD be the only entity with encryption keys, but that access does not define it.

2023-05-21 09:45 UTC, kixelated commented on draft-lcurley-warp.md
>  abbrev: WARP
I made a separate PR to do the rename (#161), and it looks like Github can show the diff correctly.

2023-05-21 19:14 UTC, suhasHere commented on draft-lcurley-warp.md
>  abbrev: WARP
As agreed on the authors call, lets keep the word "media" here

2023-05-21 19:15 UTC, suhasHere commented on draft-lcurley-warp.md
> +This document defines the core behavior for Warp, a live transport protocol over QUIC.
As agreed on the authors call, lets keep the word "media" here

2023-05-21 19:16 UTC, suhasHere commented on draft-lcurley-warp.md
> -Warp is a live media transport protocol that utilizes the QUIC network protocol {{QUIC}},
As agreed on the authors call, lets keep the word "media" here

2023-05-21 19:16 UTC, suhasHere commented on draft-lcurley-warp.md
> +* {{objects}} covers how data is fragmented into objects.
s/data/application data/

2023-05-21 19:16 UTC, suhasHere commented on draft-lcurley-warp.md
> +* {{stream-mapping}} covers how QUIC is used to transfer data.
s/data/application data

2023-05-21 20:57 UTC, suhasHere commented on draft-lcurley-warp.md
duplicate text

2023-05-21 23:13 UTC, suhasHere approved these changes

2023-05-21 23:37 UTC, merged