rewrite introduction
kixelated/warp-draft pull request #169
Opened 2023-05-25 05:19 UTC by fluffy

2023-05-25 05:33 UTC, suhasHere approved these changes
Looks fine . It would be nice if editorial nits are addressed as you see appropriate

2023-05-25 05:33 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +MoQTransport (MoQT) is a transport protocol that utilizes the QUIC
s/MoQT/moqt/g

2023-05-25 05:33 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +supports live, as well as near-live and Video on Demand (VOD)
live, interactive, as well as near-live ....

2023-05-25 15:17 UTC, kixelated requested changes

2023-05-25 18:03 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +supports live, as well as near-live and Video on Demand (VOD)
+1

2023-05-25 18:04 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +supports live, as well as near-live and Video on Demand (VOD)
I would suggest we edit it as

 MoQT
supports live, interactive use-cases.

I don;t understand near-live though

2023-05-26 02:03 UTC, fluffy commented on draft-lcurley-moq-transport.md
> +distribution. In live mode, MoQT facilitates a broad spectrum of latency
I missed this, I agree we should pick some word other than "live mode"

2023-05-26 05:18 UTC, suhasHere commented
@kixelated does the latest commit address your feedback? thanks

2023-05-26 14:05 UTC, fluffy reviewed
LGTM

2023-05-26 15:33 UTC, afrind reviewed
lgtm modulo addressing Luke's comment.

2023-05-26 15:33 UTC, afrind commented on draft-lcurley-moq-transport.md
> +policies for discovery, subscription and congestion response.
Streaming formats might specify strategies for setting priorities, or for producer congestion response - the sentence says "policies for..."  What's the right finessing here?

2023-05-26 17:21 UTC, kixelated approved these changes

2023-05-26 17:21 UTC, merged