add new terminology
kixelated/warp-draft pull request #171
Opened 2023-05-25 05:19 UTC by fluffy

2023-05-25 05:40 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +: The original producer or the final consumer in a transmission chain.
Suggest split this into 2 terms

Producer : The original producer of the media.
Consumer: the final consumer of the media.

2023-05-25 05:40 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +
remove last sentence and add reference to the group ?

2023-05-25 05:52 UTC, fluffy commented on draft-lcurley-moq-transport.md
> +
I thought we had come to "SHOULD NOT" depend.

2023-05-25 05:52 UTC, fluffy commented on draft-lcurley-moq-transport.md
> +: A temporal sequence of objects. A group represents a subscription point in a track. The media data within the group must not depend on the data in any other groups.
I have a slight preference for "join point" instead of "subscription point"

2023-05-25 15:43 UTC, kixelated requested changes

2023-05-25 15:43 UTC, kixelated commented on draft-lcurley-moq-transport.md
> +: The original producer or the final consumer in a transmission chain.
This is does not match my understand of "endpoint". A QUIC endpoint is a client or a server.

2023-05-25 15:43 UTC, kixelated commented on draft-lcurley-moq-transport.md
> +: A temporal sequence of objects. A group represents a subscription point in a track. The media data within the group must not depend on the data in any other groups.
IMO keep this definition simple and link to the section in the object model. No need to describe all properties of a group up here.

> The media data within the group must not depend on the data in any other groups.

We agreed to remove any mention of dependencies when updating the object/group model. Technically, audio groups depend on each other, as do video groups when intra-refresh is used.

2023-05-26 02:18 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +: The original producer or the final consumer in a transmission chain.
I think at one point, we decided to not update terminology section for -05 and update it once we discuss the entities and roles.

could we just revert these changes? @kixelated @fluffy would that work ?

2023-05-26 04:52 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +: The original producer or the final consumer in a transmission chain.
Added an OPEN ISSUE on the terminology

2023-05-26 04:59 UTC, suhasHere commented
@kixelated does the updated text with OPEN ISSUE looks about right to you. I personally feel we should revisit all the terms and get to a common understaning across the documents. For -05 an OPEN ISSUE seems like OK. thoughts ?

2023-05-26 15:43 UTC, afrind commented on draft-lcurley-moq-transport.md
> +: The original producer or the final consumer in a transmission chain.
I had the same comment as Luke on 163.  Endpoint appears 10 times in the doc though and all the references match Luke's definition (either the QUIC client or the QUIC server for a session) as I read it.

The point of the terminology is to help understand the document, so this definition is not accomplishing that.  I'd say either update the definition to match the usage, or remove the definition.  Adding this definition plus a discuss doesn't seem optimal to me.

2023-05-26 17:37 UTC, kixelated approved these changes

2023-05-26 17:37 UTC, merged