add model intro paragraph
kixelated/warp-draft pull request #173
Opened 2023-05-25 05:20 UTC by fluffy

2023-05-25 05:49 UTC, suhasHere commented on draft-lcurley-moq-transport.md
> +MoQT is a transport that moves entitites called messages
s/MoQT/moqt ?

2023-05-25 05:49 UTC, suhasHere approved these changes
editorial nit if it can be addressed, otherwise LGTM

2023-05-26 01:21 UTC, kixelated requested changes
Let's introduce the concept of control streams and data streams in another PR. But those should have nothing to do with the object model.

2023-05-26 01:21 UTC, kixelated commented on draft-lcurley-moq-transport.md
> +MoQT is a transport that moves entitites called messages
I like "MoQ Transport". If we're going to use initials, it should probably be all uppercase (ex. MOQT)

2023-05-26 01:21 UTC, kixelated commented on draft-lcurley-moq-transport.md
> +{{message}}. Messages are divided into two classes: control messages and
In the current draft, OBJECTs are messages. There's no distinction between control streams/messages and data streams/messages.

IMO the object model is meant to explain the properties of the protocol, while messages are the wire encoding of those properties. We should cover messages in another section and leave this section high level.

2023-05-26 02:00 UTC, fluffy reviewed
+1 other things people want to fix but LGTM

2023-05-26 05:27 UTC, suhasHere commented
@kixelated  please check the latest commit . thanks

2023-05-26 15:45 UTC, afrind commented
Something is wrong, this PR appears blank

2023-05-26 17:46 UTC, kixelated approved these changes

2023-05-26 17:47 UTC, merged