remove session and objects
kixelated/warp-draft pull request #177
Opened 2023-05-25 05:21 UTC by fluffy

2023-05-25 05:40 UTC, suhasHere approved these changes

2023-05-25 05:59 UTC, fluffy reviewed
I do think we should remove all this for now but wanted to at least flag it for reiview.

2023-05-26 01:23 UTC, kixelated requested changes
I don't understand this change.

2023-05-26 01:23 UTC, kixelated commented on draft-lcurley-moq-transport.md
> +# Sessions {#session}
What is a session? Why do we start with a DISCUSS object priorities? What does this even have to do with sessions...?

2023-05-26 01:51 UTC, fluffy commented on draft-lcurley-moq-transport.md
> +# Sessions {#session}
Two things happened here. First was we kept the Session and moved it to a top level session ( the ## to # ).  And 2nd things was to remove all the stuff on the left. I think the further text that was left here on Order Priorities and such get moved/removed in a different PR about priorities. It confusing to see here but it will be killed later

2023-05-26 15:48 UTC, afrind reviewed
This PR by itself doesn't make a lot of sense but I'm ok rolling with it if it's part of the grand plan

2023-05-26 17:48 UTC, kixelated approved these changes

2023-05-26 17:48 UTC, merged