update existing terminology
kixelated/warp-draft pull request #190
Opened 2023-05-25 22:10 UTC by fluffy

2023-05-25 22:30 UTC, suhasHere approved these changes

2023-05-26 01:23 UTC, fluffy reviewed
LGTM

2023-05-26 02:20 UTC, suhasHere submitted a review, later dismissed
I might be voting to not update terminology section for -05

2023-05-26 16:50 UTC, afrind reviewed
These updates to the terminology seem to be editorial only and improving clarity.

LGTM

2023-05-26 17:57 UTC, kixelated requested changes

2023-05-26 17:57 UTC, kixelated commented on draft-lcurley-moq-transport.md
> +: A QUIC endpoint receiving media over the network. This could be an endpoint or a relay.
Wrong definition of endpoint

2023-05-26 18:11 UTC, kixelated approved these changes

2023-05-26 18:12 UTC, merged